### ISSUE TITLE
Avoid using `renderMatching`

### ISSUE THREAD

**Issue by tjvr** [scratchblocks/scratchblocks-react#1]
Hey, thanks for publishing this plugin!

There's a more low-level API that would be more appropriate to use here, which would let you avoid adding temporary IDs to the DOM.

It is of course not documented anywhere, but if you look at the internals of `renderMatching`, you'll see it's basically doing this:
```js
      var code = options.read(el, options)

      var doc = options.parse(code, options)

      var svg = options.render(doc, options)

      options.replace(el, svg, doc, options)
```
You can skip the `read` and `replace` steps, which means essentially you just need:
```js
const doc = scratchblocks.parse(code, options)
const svg = scratchblocks.render(doc, options)
```
…where `code` is I guess the children of your React element. You should then be able to return `svg` directly from your render function I would guess? (Although you likely want to be careful to avoid React running it's Dom-diffing algorithm over it, because that will probably be too expensive.)

Hopefully some of that helps, and will help you make this plugin a little cleaner. It's a really useful thing to write 😅 Let me know if I can make any of this any cleaner (or you want a PR review!).

**Comment by PullJosh** [comment]
Well that certainly made things simpler! :P

**Comment by tjvr** [comment]
Nice! 🎉
